apiVersion: apps/v1
kind: Deployment
metadata:
  name: maglseven-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maglseven
  template:
    metadata:
      labels:
        app: maglseven
    spec:
      containers:
        - name: proxy
          imagePullPolicy: Always
          image: hexagonbenchmark/maglseven:dns-versioned-revproxy
          env:
            - name: BACKEND_FQDN
              value: hello-headless.default.svc.cluster.local
            - name: ROUTE_HEADER
              value: X-Room-ID
            - name: RESOLVE_INTERVAL
              value: 10s
            - name: DEST_PORT
              value: "8080"
            - name: REPLICA_COUNT
              value: "2"
            - name: MAX_JUMPS
              value: "100"
          ports:
            - containerPort: 8080
