apiVersion: v1
kind: ServiceAccount
metadata:
  name: maglseven-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maglseven-proxy
  namespace: default
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maglseven-proxy
  namespace: default
subjects:
  - kind: ServiceAccount
    name: maglseven-proxy
    namespace: default
roleRef:
  kind: Role
  name: maglseven-proxy
  apiGroup: rbac.authorization.k8s.io
